# Generated by Django 5.0.1 on 2025-02-01 11:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('LEGAL', 'Legal'), ('BUSINESS', 'Business'), ('ACADEMIC', 'Academic')], max_length=20)),
                ('content', models.TextField(help_text='Use {{placeholder}} syntax for dynamic fields')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FilledTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(default=dict, help_text='Stores user inputs for placeholders')),
                ('audio_recordings', models.JSONField(default=dict, help_text='Stores paths to audio recordings')),
                ('export_format', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'DOCX')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filled_templates', to='client.template')),
            ],
            options={
                'ordering': ['-modified_at'],
                'indexes': [models.Index(fields=['uuid'], name='client_fill_uuid_e63dac_idx'), models.Index(fields=['user', '-modified_at'], name='client_fill_user_id_155d70_idx')],
            },
        ),
    ]
