# Generated by Django 5.0.1 on 2025-02-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_template_filledtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_financial_analyzer_user',
            field=models.BooleanField(default=False),
        ),
    ]
