# Generated by Django 5.0.1 on 2024-01-30 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_category_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='client.category'),
        ),
    ]
