# Generated by Django 5.0.1 on 2024-02-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_client_company_client_date_added_client_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_namegen_user',
            field=models.BooleanField(default=False),
        ),
    ]
