# Generated by Django 5.0.1 on 2024-02-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0009_user_is_namegen_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_chitfund_owner",
            field=models.BooleanField(default=False),
        ),
    ]
