<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-02-11 00:03
=======
# Generated by Django 5.0.1 on 2024-02-10 22:42
>>>>>>> 85d3363fc61e3361175fae53437af7452a1dd83f

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("client", "0009_user_is_namegen_user"),
=======
        ('client', '0009_user_is_namegen_user'),
>>>>>>> 85d3363fc61e3361175fae53437af7452a1dd83f
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="user",
            name="is_chitfund_owner",
=======
            model_name='user',
            name='is_chitfund_owner',
>>>>>>> 85d3363fc61e3361175fae53437af7452a1dd83f
            field=models.BooleanField(default=False),
        ),
    ]
