# Generated by Django 5.0.1 on 2024-02-10 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_user_is_chitfund_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='chitfundName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='client.chitfund'),
        ),
    ]
