# Generated by Django 5.0.1 on 2024-06-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_client_chitfundname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_chatbot_user',
            field=models.BooleanField(default=False),
        ),
    ]
