# Generated by Django 5.0.1 on 2025-01-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_user_is_chatbot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_food_app_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_kuries_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_ocr_app_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_transcribe_app_user',
            field=models.BooleanField(default=False),
        ),
    ]
