# Generated by Django 5.0.1 on 2025-01-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0002_rename_file_ocrdocument_document_ocrdocument_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrdocument',
            name='raw_markdown',
            field=models.TextField(blank=True),
        ),
    ]
