# Generated by Django 5.0.1 on 2025-02-23 14:39

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('financial_analyzer', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
    ]
