# Generated by Django 5.0.1 on 2024-02-01 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoptions',
            name='options',
        ),
        migrations.RemoveField(
            model_name='appoptions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='appoptions',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
