# Generated by Django 5.0.1 on 2025-02-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaw', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='template',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user_inputs',
        ),
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='template_source',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
