# Generated by Django 5.0.1 on 2025-03-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='form_template',
            field=models.CharField(default='default_form.html', max_length=255),
        ),
        migrations.AddField(
            model_name='template',
            name='success_message',
            field=models.CharField(blank=True, default='Form submitted successfully', max_length=255),
        ),
        migrations.AddField(
            model_name='template',
            name='success_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
