# Generated by Django 5.0.1 on 2025-02-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaw', '0003_templatevariable_document_created_by_document_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='unique_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
